config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find_by(id: params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = 'Kitten added!'
      redirect_to kittens_path
    else
      flash[:error] = 'Invalid form fields.'
      render 'new'
    end
  end

  def update
    @kitten = Kitten.find_by(id: params[:id])
    if @kitten.update(kitten_params)
      flash[:success] = 'Kitten updated!'
      redirect_to @kitten
    else
      flash.now[:error] = 'Invalid form fields.'
      render 'new'
    end
  end

  def destroy
    @kitten = Kitten.find_by(id: params[:id])
    if @kitten.destroy
      flash[:success] = 'Kitten deleted.'
      redirect_to kittens_path
    else
      flash.now[:error] = 'An error occurred.'
    end
  end

  def edit
    @kitten = Kitten.find_by(id: params[:id])
  end

  private

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<div>
	<%= form_with model: @kitten, url: yield(:path), local: true do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %><br>
		
		<%= f.label :age %>
		<%= f.number_field :age, in: 1..20 %><br>

		<%= f.label :cuteness %>
		<%= f.number_field :cuteness, in: 1.0..10.0, step: 0.1 %><br>

		<%= f.label :softness %>
		<%= f.number_field :softness, in: 1.0..10.0, step: 0.1 %><br>

		<%= f.submit yield(:submit) %>
	<% end %>
</div>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<% provide(:path, kitten_path) %>
<% provide(:submit, "Update!") %>
<div>
	<h1>Change <%= @kitten.name %></h1>
	<div>
		<%= render 'form' %>
	</div>
</div>

app/views/kittens/index.html.erb
<div>
	<h1>All the kittens!</h1>
	<a href="<%= new_kitten_path %>">Add a kitten</a>
	<div>
		<ul>
			<% @kittens.each do |k| %>
				<li>
					<h3><%= link_to k.name, k %></h3>
					<span>Age: <%= k.age %></span><br>
					<span>Cuteness: <%= k.cuteness %></span><br>
					<span>Softness: <%= k.softness %></span>
					<%= link_to 'Delete kitten', k, method: :delete %>
				</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/kittens/new.html.erb
<% provide(:path, kittens_path) %>
<% provide(:submit, "Create!") %>
<div>
	<h1>Create a kitten</h1>
	<div>
		<%= render 'form' %>
	</div>
</div>

app/views/kittens/show.html.erb
<div>
	<h1><%= @kitten.name %>'s page</h1>
	<div>
		<span>Age: <%= @kitten.age %></span>
		<span>Cuteness: <%= @kitten.cuteness %></span>
		<span>Softness: <%= @kitten.softness %></span>
	</div>
	<%= link_to 'Edit kitten', edit_kitten_path %>
	<%= link_to 'Delete kitten', kitten_path, method: :delete %>
</div>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <span class="<%= type %>"><%= msg %></span>
    <% end %>
    <%= yield %>
  </body>
</html>